### ISSUE TITLE
Backbone isn't connecting to Django REST Framework

### ISSUE THREAD

**Issue by WilliamQLiu** [AxiaCore/todomvc-django#1]
Hi, I looked briefly at the code and it doesn't look like backbone.js is using Django REST Framework at all.  Under 'templates > backbone > js > collections > todo.js' and 'templates > backbone > js > models > todo.js', it looks like you use 'Backbone.LocalStorage' instead of pointing to the Django REST Framework url.  Is this by design?  If so, the description of "TodoMVC Backend Using Django Rest Framework" might seem a little misleading.  Thanks for taking the time to open source this though; I'm sure it's helped others understand the folder layout.

Edited: Just wanted to mention I'm new to Backbone.js so let me know if I'm misunderstanding how this is working.  Thanks!

**Comment by camilonova** [comment]
@PabloVallejo can you take a look?

**Comment by PabloVallejo** [comment]
@camilonova @WilliamQLiu, let me take a look :+1:

**Comment by PabloVallejo** [comment]
Hi @WilliamQLiu you're right, we're using Backbone.LocalStorage, however, if you want Backbone to consume the API you just have to specify the `url` attribute in the `todo` model. Which would be `api/tasks/`.

The API schema is:
- GET `api/tasks/`
- POST `api/tasks/`
- PUT `api/tasks/:id`
- DELETE `api/tasks/:id`

Let me know if this helps you.
